version: NetSort_{branch}_{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_BRANCH.$(Get-Date -format yyyy.MM.dd.ss)"
build_script:
- cmd: >-
    cd src

    dotnet restore

    dotnet test NetSort.Tests\Netsort.Tests.csproj
    
    dotnet build -c release
    
    dotnet pack NetSort\NetSort.csproj -o ..\
test: off
artifacts:
- path: src/NetSort.*.nupkg
  name: NugetPackage